### ISSUE TITLE
Suggestion: Themeable

### ISSUE THREAD

**Issue by kevinSuttle** [nkbt/react-swap#32]
Something like this would be handy to merge a `data-ui-theme` or something into props, optionally supplying an overriding, enumerated value.

**Comment by nkbt** [comment]
I usually use react-css-themr. Might be a good idea, though since react
swap does not have any own elements - there is no sense doing it. Swap
renders elements that are passed to it as is, so you are free to style them
any possible way.

**Comment by nkbt** [comment]
If you still think it makes sense to theme react-swap, please feel free to reopen issue in the new monorepo https://github.com/nkbt/react-works
